/**
 * Otito API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@ayinke.ventures
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ServerApprespApplication from "./ServerApprespApplication";

/**
 * The ServerAppresp model module.
 * @module model/ServerAppresp
 * @version 0.1.0
 */
class ServerAppresp {
  /**
   * Constructs a new <code>ServerAppresp</code>.
   * @alias module:model/ServerAppresp
   */
  constructor() {
    ServerAppresp.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>ServerAppresp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServerAppresp} obj Optional instance to populate.
   * @return {module:model/ServerAppresp} The populated <code>ServerAppresp</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServerAppresp();

      if (data.hasOwnProperty("application")) {
        obj["application"] = ServerApprespApplication.constructFromObject(
          data["application"]
        );
      }
      if (data.hasOwnProperty("message")) {
        obj["message"] = ApiClient.convertToType(data["message"], "String");
      }
      if (data.hasOwnProperty("status")) {
        obj["status"] = ApiClient.convertToType(data["status"], "Boolean");
      }
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>ServerAppresp</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServerAppresp</code>.
   */
  static validateJSON(data) {
    // validate the optional field `application`
    if (data["application"]) {
      // data not null
      ServerApprespApplication.validateJSON(data["application"]);
    }
    // ensure the json data is a string
    if (
      data["message"] &&
      !(
        typeof data["message"] === "string" || data["message"] instanceof String
      )
    ) {
      throw new Error(
        "Expected the field `message` to be a primitive type in the JSON string but got " +
          data["message"]
      );
    }

    return true;
  }
}

/**
 * @member {module:model/ServerApprespApplication} application
 */
ServerAppresp.prototype["application"] = undefined;

/**
 * Generic message that tells you the status of the operation
 * @member {String} message
 */
ServerAppresp.prototype["message"] = undefined;

/**
 * @member {Boolean} status
 */
ServerAppresp.prototype["status"] = undefined;

export default ServerAppresp;
