/**
 * Otito API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@ayinke.ventures
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ServerMessageHTTPDefinition } from '../models/ServerMessageHTTPDefinition';
import { HttpFile } from '../http/http';

export class ServerSwaggerMessageRespMessagesInner {
    'applicationId'?: string;
    'createdAt'?: string;
    'id'?: string;
    /**
    * This is for the request
    */
    'ipAddress'?: string;
    'method'?: string;
    'organisationId'?: string;
    'path'?: string;
    'reference'?: string;
    'request'?: ServerMessageHTTPDefinition;
    'response'?: ServerMessageHTTPDefinition;
    'statusCode'?: number;
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "applicationId",
            "baseName": "application_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "ipAddress",
            "baseName": "ip_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string",
            "format": ""
        },
        {
            "name": "organisationId",
            "baseName": "organisation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "ServerMessageHTTPDefinition",
            "format": ""
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "ServerMessageHTTPDefinition",
            "format": ""
        },
        {
            "name": "statusCode",
            "baseName": "status_code",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServerSwaggerMessageRespMessagesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

