/**
 * Otito API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@ayinke.ventures
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ServerSwaggerMessageRespMessagesInner } from '../models/ServerSwaggerMessageRespMessagesInner';
import { HttpFile } from '../http/http';

export class ServerSwaggerMessageResp {
    'messages'?: Array<ServerSwaggerMessageRespMessagesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<ServerSwaggerMessageRespMessagesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServerSwaggerMessageResp.attributeTypeMap;
    }

    public constructor() {
    }
}

